### ISSUE TITLE
Request: Local app

### ISSUE THREAD

**Issue by eryeden** [miyanokomiya/no-mans-folly#15]
Thank you for sharing this great app! I would like to request a local version similar to draw.io. Thanks!

**Comment by miyanokomiya** [comment]
Hello @eryeden and thanks for you request. Making the app standalone application is a good idea and is actually in the backlog. But for now, it isn't much prioritized yet.

As a workaround until it's done, the app supports PWA so it can be installed as app. I tweaked the setting today and now it works offline as well. Hope this'll help you.
This is the document that I also added just now.
https://doc.no-mans-folly.com/offline.html

**Comment by eryeden** [comment]
Thanks! PWA worked perfectly for me.
